#!/usr/bin/perl

use strict;
use warnings;

sub check_element {
    my ($element,@list) = @_;
    foreach (@list) {
        if ($element eq $_){
            print "We have $_ here , hurray!\n";
        }
    }
}

my @list_names = qw/ kevin typer aladin lan ti albert /;
my $name = 'kevin';

&check_element($name,@list_names);
